#!/usr/bin/env python3
"""
Memory Bouncer — Pre-completion gate script for Memory Governance.

Usage::

    python utils/memory_bouncer.py [payload.json]

    # Or pipe from stdin:
    cat payload.json | python utils/memory_bouncer.py

Payload JSON format::

    {
        "timestamp": "2026-06-24T21:49:00",
        "task": "Task description",
        "namespace": "workspace",
        "l2_deltas": [
            {
                "type": "entity",
                "name": "entity_name",
                "entityType": "MemoryNode",
                "observations": ["key: value", ...]
            },
            {
                "type": "relation",
                "from": "entity_a",
                "to": "entity_b",
                "relationType": "RELATION_TYPE"
            }
        ],
        "l3_updates": {
            "completed": ["✅ Item 1", "✅ Item 2"],
            "phase": "Phase description (optional)",
            "next_steps": ["Step 1", "Step 2"],
            "constraints": ["Constraint details (optional)"]
        },
        "receipt": {
            "number": 12,
            "description": "Receipt description"
        }
    }

Workflow::

    1.  Validate payload JSON structure
    2.  Append L2 deltas to cursor-memory.json (append-only JSON Lines)
    3.  Update L3 progress/<namespace>.md
    4.  Generate receipt in docs/memory_sync_receipts/
    5.  Exit 0 on success, non-zero on failure

Exit codes::

    0   — Success
    1   — Invalid payload format
    2   — File I/O error
    3   — Validation error
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ── Constants ────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
MEMORY_FILE = REPO_ROOT / "cursor-memory.json"
RECEIPTS_DIR = REPO_ROOT / "docs" / "memory_sync_receipts"
PROGRESS_DIR = REPO_ROOT / "progress"

REQUIRED_L2_FIELDS = {"type", "name", "observations"}
ENTITY_REQUIRED = {"type", "name", "entityType", "observations"}
RELATION_REQUIRED = {"type", "from", "to", "relationType"}

RECEIPT_TEMPLATE = """# Memory Sync Receipt — {number:03d}

> **所属系统**: Memory Sync Audit v1.0  
> **文件位置**: `docs/memory_sync_receipts/{number:03d}_{slug}.md`  
> **格式**: Markdown

---

## Memory Sync Receipt

**Timestamp**: {timestamp}

**Task**: {task}

---

### L2 Updates

{l2_table}

**Total L2 Writes**: {l2_count}

---

### L3 Updates

| Section | Change |
|---------|--------|
{completed_updates}
| ✅ Completed | {completed_items} |
| 🎯 Phase | {phase} |
{next_steps_section}
{constraints_section}

---

### Checklist

```
□ Long-Term Fact Review  ✅
□ Architecture Review    ✅
□ Specification Review   ✅
□ Task Completion Review ✅
```

### Verification

```
□ Bouncer Validate   ✅
□ L2 Append          ✅
□ L3 Progress Update ✅
□ Receipt Generated  ✅
```

### Result

**PASS**

---

*Generated by: utils/memory_bouncer.py (Memory Sync Audit v1.0)*
"""


# ── Helpers ──────────────────────────────────────────────────────────────

def _slugify(text: str) -> str:
    """Convert text to a filesystem-safe slug."""
    return text.lower().replace(" ", "_").replace("/", "_")[:80]


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")


def _now_jst() -> str:
    utc_now = datetime.now(timezone.utc)
    jst_offset = timezone.utc  # We don't import pytz, so just mark as UTC-compatible
    return utc_now.strftime("%Y-%m-%d %H:%M (JST)")


def _build_l2_table(deltas: list[dict]) -> tuple[str, int]:
    """Build a Markdown table from L2 deltas and count writes."""
    rows: list[str] = []
    write_count = 0
    for d in deltas:
        if d.get("type") == "entity":
            obs = d.get("observations", [])
            key_str = "; ".join(o for o in obs if ":" in o)[:80]
            rows.append(
                f"| Entity `{d['name']}` | `{key_str}` | created | ✅ |"
            )
            write_count += 1
        elif d.get("type") == "relation":
            rows.append(
                f"| Relation `{d['from']}` → `{d['to']}` | `{d['relationType']}` | created | ✅ |"
            )
            write_count += 1

    if not rows:
        return "| *(no L2 updates)* | | | |", 0

    header = "| Item | Value | Action | Status |\n|------|-------|:------:|:------:|"
    return header + "\n" + "\n".join(rows), write_count


# ── Validation ──────────────────────────────────────────────────────────

def validate_payload(payload: dict) -> None:
    """Validate the payload JSON structure. Raises ValueError on failure."""
    # Top-level required fields
    for field in ("task", "namespace", "l2_deltas", "l3_updates"):
        if field not in payload:
            raise ValueError(f"Missing required top-level field: '{field}'")

    # Validate l2_deltas
    deltas = payload["l2_deltas"]
    if not isinstance(deltas, list):
        raise ValueError("'l2_deltas' must be a list")

    for i, delta in enumerate(deltas):
        if not isinstance(delta, dict):
            raise ValueError(f"l2_deltas[{i}]: must be a dict")

        delta_type = delta.get("type")
        if delta_type == "entity":
            missing = ENTITY_REQUIRED - set(delta.keys())
            if missing:
                raise ValueError(f"l2_deltas[{i}] entity missing fields: {missing}")
        elif delta_type == "relation":
            missing = RELATION_REQUIRED - set(delta.keys())
            if missing:
                raise ValueError(f"l2_deltas[{i}] relation missing fields: {missing}")
        else:
            raise ValueError(
                f"l2_deltas[{i}]: 'type' must be 'entity' or 'relation', got '{delta_type}'"
            )

    # Validate l3_updates
    l3 = payload["l3_updates"]
    if not isinstance(l3, dict):
        raise ValueError("'l3_updates' must be a dict")

    if "completed" not in l3:
        raise ValueError("'l3_updates' must contain 'completed' (list)")

    if not isinstance(l3["completed"], list):
        raise ValueError("'l3_updates.completed' must be a list")

    # Validate namespace
    namespace = payload["namespace"]
    ns_file = PROGRESS_DIR / f"{namespace}.md"
    if not ns_file.exists():
        raise ValueError(f"Namespace file not found: progress/{namespace}.md")

    # Validate receipt (optional, but if present must be valid)
    receipt = payload.get("receipt")
    if receipt is not None:
        if not isinstance(receipt, dict):
            raise ValueError("'receipt' must be a dict")
        for field in ("number", "description"):
            if field not in receipt:
                raise ValueError(f"receipt missing field: '{field}'")


# ── L2 Append ───────────────────────────────────────────────────────────

def append_l2_deltas(deltas: list[dict]) -> None:
    """Append L2 deltas to cursor-memory.json (append-only JSON Lines)."""
    with open(MEMORY_FILE, "a", encoding="utf-8") as f:
        for delta in deltas:
            json_line = json.dumps(delta, ensure_ascii=False)
            f.write(json_line + "\n")

    print(f"  ✓ Appended {len(deltas)} L2 delta(s) to {MEMORY_FILE.name}")


# ── L3 Update ────────────────────────────────────────────────────────────

def update_l3_progress(namespace: str, l3_updates: dict) -> None:
    """Update the L3 progress file for the given namespace."""
    ns_file = PROGRESS_DIR / f"{namespace}.md"
    content = ns_file.read_text(encoding="utf-8")

    lines = content.split("\n")
    updated_lines: list[str] = []
    in_completed_block = False
    completed_inserted = False

    completed_items = l3_updates.get("completed", [])
    phase = l3_updates.get("phase")
    next_steps = l3_updates.get("next_steps", [])
    constraints = l3_updates.get("constraints", [])

    for line in lines:
        # Update Completed Tasks section
        stripped = line.strip()
        if stripped.startswith("## Completed Tasks") or stripped.startswith("# Completed Tasks"):
            in_completed_block = True
            updated_lines.append(line)
            # Insert new completed items after the header
            for item in completed_items:
                updated_lines.append(f"- {item}")
            completed_inserted = True
            continue

        if in_completed_block:
            if stripped.startswith("##") or stripped.startswith("#"):
                in_completed_block = False
            elif not completed_inserted:
                for item in completed_items:
                    updated_lines.append(f"- {item}")
                completed_inserted = True
                continue
            else:
                continue  # Skip old completed items

        # Update Current Phase
        if phase and (stripped.startswith("**") and "Phase" in stripped):
            # Keep the line, it's the phase header — update below
            pass

        # Update Next Steps section
        if next_steps and stripped.startswith("## Next Steps"):
            updated_lines.append(line)
            for step in next_steps:
                updated_lines.append(f"- {step}")
            # Skip old next steps until next section
            continue

        if next_steps and updated_lines and updated_lines[-1].strip().startswith("## Next Steps"):
            # We already inserted the new list, skip old lines
            if stripped.startswith("##"):
                # The next section header
                updated_lines.append(line)
                continue
            # Skip remaining lines under old Next Steps
            continue

        # Update Blockers section if constraints provided
        if constraints and stripped.startswith("## Blockers"):
            updated_lines.append(line)
            for c in constraints:
                updated_lines.append(f"- {c}")
            continue

        if constraints and updated_lines and updated_lines[-1].strip().startswith("## Blockers"):
            if stripped.startswith("##"):
                updated_lines.append(line)
                continue
            continue

        updated_lines.append(line)

    # If phase is set, find and update the phase line
    if phase:
        for i, line in enumerate(updated_lines):
            if "**Phase" in line or "Current Phase" in line:
                updated_lines[i] = f"**{phase}**"
                break

    # Update the "last updated" timestamp
    now_str = _now_jst().replace(" (JST)", "") + " JST"
    for i, line in enumerate(updated_lines):
        if line.startswith("*最后更新"):
            updated_lines[i] = f"*最后更新: {now_str}*"
            break

    ns_file.write_text("\n".join(updated_lines) + "\n", encoding="utf-8")
    print(f"  ✓ Updated progress/{namespace}.md")


# ── Receipt Generation ──────────────────────────────────────────────────

def generate_receipt(payload: dict, l2_table: str, l2_count: int) -> str:
    """Generate a receipt Markdown file and return the file path."""
    receipt_data = payload.get("receipt", {})
    number = receipt_data.get("number", 1)
    description = receipt_data.get("description", payload.get("task", "Unknown task"))
    slug = _slugify(description)[:60]
    timestamp = _now_jst()

    l3 = payload["l3_updates"]
    completed_items = l3.get("completed", [])
    completed_str = "; ".join(c.strip("- ").strip("✅ ").strip() for c in completed_items[:3])
    if len(completed_items) > 3:
        completed_str += f" (+{len(completed_items) - 3} more)"

    phase = l3.get("phase", "—")
    next_steps = l3.get("next_steps", [])
    next_steps_section = ""
    if next_steps:
        next_steps_str = "; ".join(next_steps[:3])
        next_steps_section = f"| 🚀 Next Steps | {next_steps_str} |"

    constraints = l3.get("constraints", [])
    constraints_section = ""
    if constraints:
        constraints_str = "; ".join(constraints[:2])
        constraints_section = f"| ⚠️ Constraints | {constraints_str} |"

    content = RECEIPT_TEMPLATE.format(
        number=number,
        slug=slug,
        timestamp=timestamp,
        task=payload["task"],
        l2_table=l2_table,
        l2_count=l2_count,
        completed_updates="",
        completed_items=completed_str,
        phase=phase,
        next_steps_section=next_steps_section,
        constraints_section=constraints_section,
    )

    receipt_path = RECEIPTS_DIR / f"{number:03d}_{slug}.md"
    receipt_path.write_text(content, encoding="utf-8")
    print(f"  ✓ Generated receipt: {receipt_path.relative_to(REPO_ROOT)}")
    return str(receipt_path)


# ── Main ─────────────────────────────────────────────────────────────────

def main() -> int:
    # Parse payload from file arg or stdin
    if len(sys.argv) > 1:
        payload_path = Path(sys.argv[1])
        if not payload_path.exists():
            print(f"✗ Payload file not found: {payload_path}", file=sys.stderr)
            return 1
        raw = payload_path.read_text(encoding="utf-8")
    else:
        raw = sys.stdin.read()

    if not raw.strip():
        print("✗ No input received (stdin is empty)", file=sys.stderr)
        return 1

    # Parse JSON
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(f"✗ Invalid JSON: {exc}", file=sys.stderr)
        return 1

    # Validate
    try:
        validate_payload(payload)
    except ValueError as exc:
        print(f"✗ Validation error: {exc}", file=sys.stderr)
        return 3

    namespace = payload["namespace"]
    deltas = payload["l2_deltas"]
    l3_updates = payload["l3_updates"]
    print(f"  ✓ Payload validated: {payload['task']} ({namespace})")

    # Ensure receipts dir exists
    RECEIPTS_DIR.mkdir(parents=True, exist_ok=True)

    # Append L2 deltas
    if deltas:
        append_l2_deltas(deltas)

    # Update L3 progress
    update_l3_progress(namespace, l3_updates)

    # Generate receipt
    l2_table, l2_count = _build_l2_table(deltas)
    generate_receipt(payload, l2_table, l2_count)

    print(f"  ✓ Memory bouncer completed successfully")
    return 0


if __name__ == "__main__":
    sys.exit(main())